let
    Source = Excel.Workbook(File.Contents("D:\Power BI\Query\EmployeeData.xlsx"), null, true),
    EmployeeData1_Sheet = Source{[Item="EmployeeData1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(EmployeeData1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmployeeID", Int64.Type}, {"NationalIDNumber", Int64.Type}, {"ContactID", Int64.Type}, {"LoginID", type text}, {"ManagerID", Int64.Type}, {"Title", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"HireDate", type date}, {"Dept", type text}, {"Salary", Int64.Type}, {"Job Grade", type text}, {"CurrentFlag", Int64.Type}, {"rowguid", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"NationalIDNumber", "ContactID"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"EmployeeID", "ManagerID", "Title", "BirthDate", "MaritalStatus", "Gender", "HireDate", "Dept", "Salary", "Job Grade"}),
    #"Inserted Lowercased Text" = Table.AddColumn(#"Removed Other Columns", "lowercase", each Text.Lower([Title]), type text),
    #"Inserted Uppercased Text" = Table.AddColumn(#"Inserted Lowercased Text", "UPPERCASE", each Text.Upper([Title]), type text),
    #"Inserted Capitalize Each Word" = Table.AddColumn(#"Inserted Uppercased Text", "Capitalize Each Word", each Text.Proper([lowercase]), type text),
    #"Inserted Prefix" = Table.AddColumn(#"Inserted Capitalize Each Word", "Prefix", each "Mr. " & [Capitalize Each Word], type text),
    #"Inserted Age" = Table.AddColumn(#"Inserted Prefix", "Age", each Date.From(DateTime.LocalNow()) - [BirthDate], type duration),
    #"Calculated Total Years" = Table.TransformColumns(#"Inserted Age",{{"Age", each Duration.TotalDays(_) / 365, type number}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Calculated Total Years",{{"Age", Int64.Type}}),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type1", "Text Before Delimiter", each Text.BeforeDelimiter([Title], " "), type text),
    #"Inserted Text After Delimiter" = Table.AddColumn(#"Inserted Text Before Delimiter", "Text After Delimiter", each Text.AfterDelimiter([Title], " "), type text),
    #"Replaced Value" = Table.ReplaceValue(#"Inserted Text After Delimiter","M","Married",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","S","Single",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","M","Male",Replacer.ReplaceText,{"Gender"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","F","Female",Replacer.ReplaceText,{"Gender"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Replaced Value3",{"Prefix"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Columns1", each true),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Filtered Rows", "Title", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Title.1", "Title.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Title.1", type text}, {"Title.2", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Title.1", "First Name"}, {"Title.2", "Second Name"}}),
    #"Merged Columns" = Table.CombineColumns(#"Renamed Columns",{"First Name", "Second Name"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Merged"),
    #"Renamed Columns1" = Table.RenameColumns(#"Merged Columns",{{"Merged", "Title"}}),
    #"Inserted Text Between Delimiters" = Table.AddColumn(#"Renamed Columns1", "Text Between Delimiters", each Text.BetweenDelimiters(Text.From([BirthDate], "en-IN"), "-", "-"), type text),
    #"Duplicated Column" = Table.AddColumn(#"Inserted Text Between Delimiters", "Dept - Copy", each [Dept], type text),
    #"Added Conditional Column" = Table.AddColumn(#"Duplicated Column", "Custom", each if [Gender] = "Male" then "Mr." else if [MaritalStatus] = "Single" then "MS" else if [MaritalStatus] = "Married" then "Mrs" else null),
    #"Inserted Merged Column" = Table.AddColumn(#"Added Conditional Column", "Merged", each Text.Combine({[Custom], [Title]}, " "), type text),
    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Merged Column",{{"Merged", "Full Name"}}),
    #"Inserted Age1" = Table.AddColumn(#"Renamed Columns2", "Age.1", each Date.From(DateTime.LocalNow()) - [BirthDate], type duration),
    #"Inserted Total Years" = Table.AddColumn(#"Inserted Age1", "Total Years", each Duration.TotalDays([Age.1]) / 365, type number),
    #"Changed Type3" = Table.TransformColumnTypes(#"Inserted Total Years",{{"Total Years", Int64.Type}})
in
    #"Changed Type3"